# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChatbot():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chatbot(self):
    self.driver.get("http://127.0.0.1:5001/")
    self.driver.set_window_size(1288, 1039)
    self.driver.find_element(By.ID, "intro-button").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "prev").click()
    self.driver.find_element(By.ID, "prev").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.ID, "next").click()
    self.driver.find_element(By.LINK_TEXT, "Purpose").click()
    self.driver.find_element(By.ID, "tutorial-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "#video-modal > .close-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".signup-button:nth-child(2)").click()
    self.driver.find_element(By.ID, "username-signup").click()
    self.driver.find_element(By.ID, "username-signup").send_keys("testuser123")
    self.driver.find_element(By.ID, "password-signup").send_keys("testuser123")
    self.driver.find_element(By.ID, "re-password-signup").send_keys("testuser123")
    self.driver.find_element(By.CSS_SELECTOR, ".form-element:nth-child(5) #btn").click()
    self.driver.find_element(By.ID, "password-login").click()
    self.driver.find_element(By.ID, "password-login").send_keys("testuser123")
    self.driver.find_element(By.ID, "password-login").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#intro-button > .btn-primary").click()
    self.driver.find_element(By.ID, "jobTitle").click()
    self.driver.find_element(By.ID, "jobTitle").send_keys("bricklayer")
    self.driver.find_element(By.ID, "jobTitleSubmit").click()
    self.driver.find_element(By.ID, "userInput").click()
    self.driver.find_element(By.ID, "userInput").send_keys("none")
    self.driver.find_element(By.ID, "userInput").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "userInput").click()
    self.driver.find_element(By.ID, "userInput").send_keys("no")
    element = self.driver.find_element(By.ID, "sendBtn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".input-group-chatbox")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".input-group-chatbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link").click()
    self.driver.find_element(By.ID, "filterJobTitle").click()
    self.driver.find_element(By.ID, "filterRating").send_keys("1")
    self.driver.find_element(By.ID, "filterRating").click()
    self.driver.find_element(By.ID, "filterRating").send_keys("2")
    self.driver.find_element(By.ID, "filterRating").click()
    self.driver.find_element(By.ID, "filterRating").send_keys("3")
    self.driver.find_element(By.ID, "filterRating").click()
    element = self.driver.find_element(By.ID, "filterRating")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".chat-container").click()
    self.driver.find_element(By.ID, "filterRating").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#dropdownUser1 > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, "form:nth-child(1) > .dropdown-item").click()
    self.driver.find_element(By.CSS_SELECTOR, "#intro-button > .btn-primary").click()
    self.driver.find_element(By.ID, "dropdownUser1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#login-buttons > .dropdown-item").click()